[project]
name = "kv-cache"
version = "0.1.0"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = "-q"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E","F","I","SIM","PIE","UP"]
fix = true
